### PR TITLE
Bump to latest api-generator-sifive, wit, and wake

### PR DESCRIPTION
**Pull request by richardxia**
In addition to bumping the versions of the repos mentioned in the title, this also changes the CI setup away from Travis CI to GitHub Actions so that we can make use of the handy Actions that we defined for wit and wake.

My real intent behind this is to get it up to date enough so that I can tear out the scribble/documentation generation workflow from api-generator-sifive.

BTW, it looks like we haven't tagged a release of this repo in a while. I'm not sure if we're still interested in doing that, even retroactively, but I saw unpublished changes in the CHANGELOG related to bumping the environment-blockci-sifive version. I just overwrote it with the current latest version (0.3.0 -> 0.8.0).

This was tested locally by running the `runSim` and `makeOnboardingDocument` targets, but I don't have an easy way of testing the GH Actions changes other than submitting this PR, so I'll see if there are any issues after hitting the submit button here.

### CODE REVIEW

**Review by mmjconolly — APPROVED** [review]
ltgm

**Comment by richardxia** [comment]
CI failed on the RISC-V software compilation, which is probably because I bumped to too new of an environment-blockci-sifive for the existing wake rules. We probably can't use [environment-blockci-sifive v0.8.0](https://github.com/sifive/environment-blockci-sifive/releases/tag/0.8.0), which uses the 2020.08.2 version of the GNU toolchain, until https://github.com/sifive/freedom-e-sdk/pull/528 merges in and api-generator-sifive is updated.

Let me try bumping it back to 0.7.1 to see if it passes.

**Review by albertchen-sifive — APPROVED** [review]
LGTM

**Comment by richardxia** [comment]
Looks like I have to close and reopen this PR or something since I can't swap the branch protections rules to require the new GitHub Actions check, since it was over a week ago and GitHub only lists status checks that ran within the last week in the list of checks you can require.

**Pull request merged**
